CREATE TABLE FOOD(
F_ID NUMBER(20),
LOCAL VARCHAR2(30),
F_NAME VARCHAR2(80),
F_PARKING CHAR(2),
F_WIFI CHAR(2),
F_MULTILANG CHAR(2),
F_DAYPOFF VARCHAR2(30),
F_OPEN_CLOSE VARCHAR2(70),
F_DELIVER CHAR(2));

CREATE TABLE HOTEL(
H_ID NUMBER(10),
LOCAL VARCHAR2(30),
H_NAME VARCHAR2(80),
H_LATITUDE NUMBER(12,8),
H_LONGITUDE NUMBER(12,8),
H_CLOSURE CHAR(2),
H_PHONE VARCHAR2(20),
H_PAGE VARCHAR2(200),
H_PARKING CHAR(2),
H_STORAGE CHAR(2),
H_WHEELCHAIR CHAR(2));

CREATE TABLE REPORTS(
R_ID NUMBER(5),
LOCAL VARCHAR2(30),
R_NAME VARCHAR2(200),
R_TYPE CHAR(15),
R_LATITUDE NUMBER(12,8),
R_LONGITUDE NUMBER(12,8),
R_PLACE VARCHAR(200),
R_TITLE CLOB,
R_PHONE VARCHAR(250),
R_PAGE CLOB,
R_DAYOFF CLOB,
R_OPEN_CLOSE CLOB,
R_PRICE CLOB,
R_DETAIL CLOB);

CREATE TABLE CULTURAL(
C_ID NUMBER(5),
LOCAL VARCHAR2(30),
C_NAME VARCHAR(100),
C_NUMBER VARCHAR(30),
C_MANAGER VARCHAR(100),
C_ERA VARCHAR(30),
C_TYPE CHAR(50),
C_DETAIL CLOB,
C_PHONE VARCHAR(20),
C_LATITUDE NUMBER(14,10),
C_LONGITUDE NUMBER(14,10));

DROP TABLE CULTURAL;